name       : lzop
version    : 1.04
release    : 2
source     :
    - https://www.lzop.org/download/lzop-1.04.tar.gz : 7e72b62a8a60aff5200a047eea0773a8fb205caf7acbe1774d95147f305a2f41
license    : GPL-2.0
component  : system.utils
summary    : lzop (Compression utility)
description: |
    lzop is a file compressor which is very similar to gzip. lzop uses the LZO data compression library for compression services, and its main advantages over gzip are much higher compression and decompression speed (at the cost of some compression ratio).
builddeps  :
  - lzo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
